// <auto-generated />
using System;
using ClinicServiceDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicServiceDAL.Migrations.Sqlite
{
    [DbContext(typeof(SqliteClinicDbContext))]
    [Migration("20260924194555_SecurityAuthentication")]
    partial class SecurityAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ClinicServiceContext.Entities.AccountSecurityState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EditDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("TwoFactorConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("AccountSecurityStates");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.AppointmentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppointmentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Doctor")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EditedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MedicalCard")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Patient")
                        .HasColumnType("TEXT");

                    b.Property<string>("PremilinaryReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "IsCurrent");

                    b.HasIndex("EntityId", "Version")
                        .IsUnique();

                    b.ToTable("AppointmentSnapshots");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.DiagnosisSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Doctor")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EditedDoctor")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcdCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MedicalCard")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "IsCurrent");

                    b.HasIndex("EntityId", "Version")
                        .IsUnique();

                    b.ToTable("DiagnosisSnapshots");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.InsuranceProviderSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "IsCurrent");

                    b.HasIndex("EntityId", "Version")
                        .IsUnique();

                    b.ToTable("InsuranceProviderSnapshots");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.MedicalCardSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Diagnoses")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Patient")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Policy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RecordNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "IsCurrent");

                    b.HasIndex("EntityId", "Version")
                        .IsUnique();

                    b.ToTable("MedicalCardSnapshots");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.PatientSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Allergies")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "IsCurrent");

                    b.HasIndex("EntityId", "Version")
                        .IsUnique();

                    b.ToTable("PatientSnapshots");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.PersonSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "IsCurrent");

                    b.HasIndex("EntityId", "Version")
                        .IsUnique();

                    b.ToTable("PersonSnapshots");

                    b.HasDiscriminator<byte>("Type").HasValue((byte)0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.PolicySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InsuranceProvider")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicalPolicyNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicalPolicyType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "IsCurrent");

                    b.HasIndex("EntityId", "Version")
                        .IsUnique();

                    b.ToTable("PolicySnapshots");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("PersonId", "RevokedAt");

                    b.ToTable("RefreshSessions");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Appointments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Doctor")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.SecurityAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "CreatedAt");

                    b.ToTable("SecurityAuditEvents");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.SpecialisationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Doctors")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "IsCurrent");

                    b.HasIndex("EntityId", "Version")
                        .IsUnique();

                    b.ToTable("SpecialisationSnapshots");
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.Administrator", b =>
                {
                    b.HasBaseType("ClinicServiceContext.Entities.PersonSnapshot");

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("ClinicServiceContext.Entities.Doctor", b =>
                {
                    b.HasBaseType("ClinicServiceContext.Entities.PersonSnapshot");

                    b.Property<int>("EmployeeWorkStatus")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Specialisations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue((byte)2);
                });
#pragma warning restore 612, 618
        }
    }
}
